language: python
python:
  - "2.6"
  - "2.7"
script: nosetests
env:
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.4
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
script: django-admin.py test maintenance --settings=maintenance.tests.test_settings
